name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install TA-Lib dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ta-lib-dev
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint with black
      run: |
        black --check user_data/strategies/ scripts/ tests/
    
    - name: Sort imports with isort
      run: |
        isort --check-only user_data/strategies/ scripts/ tests/
    
    - name: Type checking with mypy
      run: |
        mypy user_data/strategies/ scripts/ --ignore-missing-imports
    
    - name: Test with pytest
      run: |
        pytest tests/ -v --tb=short
    
    - name: Validate strategy
      run: |
        python -c "from user_data.strategies.donchian_atr import DonchianATRTrend; print('Strategy validation passed')"

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Bandit Security Scan
      uses: securecodewarrior/github-action-bandit@v1.0.1
      with:
        config_file: .bandit
        
    - name: Check for secrets
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD
